config/routes.rb
Glider::Application.routes.draw do
  resources :deal_members


  resources :inviteds
  resources :companies
  resources :comments
  resources :signatures
  resources :get_signatures
  resources :approvals
  resources :request_docs
  resources :uploads
  resources :deals

  match '/about',           to: 'static_pages#about'
  match '/contact',         to: 'static_pages#contact'
  match '/help',            to: 'static_pages#help'
  match '/documentation',   to: 'static_pages#documentation'
  match '/terms',           to: 'static_pages#terms'

  mount StripeEvent::Engine => '/stripe'
  get "content/gold"
  get "content/silver"
  get "content/platinum"
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  match '/pricing',           to: 'home#pricing'
  devise_for :users, :controllers => { :registrations => 'registrations' }
  devise_scope :user do
    put 'update_plan', :to => 'registrations#update_plan'
    put 'update_card', :to => 'registrations#update_card'
  end
  resources :users
end

app/models/deal.rb
class Deal < ActiveRecord::Base
  attr_accessible :name

  belongs_to :companies
  has_many :users, :through => :deal_members
  has_one :uploads
  has_many :approvals
  has_many :comments
  has_many :signatures
  has_many :request_docs
  has_many :inviteds
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  # GET /deals
  # GET /deals.json
  def index
    @deals = Deal.all
    @companies = Company.all
    @approvals = Approval.all
    @comments = Comment.all
    @get_signatures = GetSignature.all
    @signatures = Signature.all
    @uploads = Upload.all
    @inviteds = Invited.all
    @request_docs = RequestDoc.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @deals }
    end
  end

  # GET /deals/1
  # GET /deals/1.json
  def show
    @deal = Deal.find(params[:id])
    @company = Company.find(params[:id])
    @approvals = Approval.find(params[:id])
    @comments = Comment.find(params[:id])
    @get_signatures = GetSignature.find(params[:id])
    @signature = Signature.find(params[:id])
    @upload = Upload.find(params[:id])
    @invited = Invited.find(params[:id])   
    @request_doc = RequestDoc.find(params[:id])



    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @deal }
    end
  end

  # GET /deals/new
  # GET /deals/new.json
  def new
    @deal = Deal.new
    @company = Company.new
    @approval = Approval.new
    @comment = Comment.new
    @get_signature = GetSignature.new
    @signature = Signature.new
    @upload = Upload.new
    @invited = Invited.new
    @request_doc = RequestDoc.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @deal }
    end
  end

  # GET /deals/1/edit
  def edit
    @deal = Deal.find(params[:id])
  end

  # POST /deals
  # POST /deals.json
  def create
    @deal = Deal.new(params[:deal])

    respond_to do |format|
      if @deal.save
        format.html { redirect_to @deal, notice: 'Deal was successfully created.' }
        format.json { render json: @deal, status: :created, location: @deal }
      else
        format.html { render action: "new" }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /deals/1
  # PUT /deals/1.json
  def update
    @deal = Deal.find(params[:id])

    respond_to do |format|
      if @deal.update_attributes(params[:deal])
        format.html { redirect_to @deal, notice: 'Deal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deals/1
  # DELETE /deals/1.json
  def destroy
    @deal = Deal.find(params[:id])
    @deal.destroy

    respond_to do |format|
      format.html { redirect_to deals_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/views/deals/_approvals.html.erb
<div id="approvals_container" style="display: none">
	<div id="approvals">
		<%= simple_form_for(@approval) do |f| %>
		  <%= f.error_notification %>

		  <div class="form-inputs">
		    <%= f.input :names, placeholder: 'names of those to approve', label: false %>
		    <%= f.input :by_date %>
		    <%= f.text_area :description, label: false, placeholder:'Notes' %>
		  </div>

		  <div class="form-actions" style="display: none">
		    <%= f.button :submit %>
		  </div>
		<% end %>
	</div>
</div>

app/views/deals/_comments.html.erb
<div id="comments_container" style="display: none">
	<div id="comments">
		<%= simple_form_for(@comment) do |f| %>
		  <%= f.error_notification %>

		  <div class="form-inputs">
		    <%= f.input :deal_id %>
		    <%= f.input :comments %>
		  </div>

		  <div class="form-actions">
		    <%= f.button :submit %>
		  </div>
		<% end %>
	</div>
</div>

app/views/deals/_company.html.erb
<div id="company_container">
	<div id="companies">
		<%= simple_form_for(@company) do |f| %>
		  <%= f.error_notification %>

		  <div class="form-inputs">
		    <%= f.input :company, placeholder: 'company name', label: false %>
		  </div>

		  <div class="form-actions" style="display: none">
		    <%= f.button :submit %>
		  </div>
		<% end %>
	</div>
</div>

app/views/deals/_deal.html.erb
<%= simple_form_for(@deal) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, placeholder: 'deal name', label: false %>
  </div>

  <div class="form-actions" style="display: none">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/deals/_getSignature.html.erb
<div id="getSignature_container" style="display: none">
	<div id="getSignature">
		<%= simple_form_for(@get_signature) do |f| %>
		  <%= f.error_notification %>

		  <div class="form-inputs">
		    <%= f.input :from, placeholder: 'get Signature from?'%>
		    <%= f.input :by_date %>
		  </div>

		  <div class="form-actions" style="display:none">
		    <%= f.button :submit %>
		  </div>
		<% end %>
	</div>
</div>

app/views/deals/_invite.html.erb
<div id="invite_container" style="display: none">
  <div id="invite">
    <%= simple_form_for(@invited) do |f| %>
      <%= f.error_notification %>

      <div class="form-inputs">
        <%= f.input :deal_id %>
        <%= f.input :email %>
        <%= f.input :full_names %>
        <%= f.input :user_type %>
      </div>

      <div class="form-actions">
        <%= f.button :submit %>
      </div>
    <% end %>
  </div>
</div>

app/views/deals/_requestDoc.html.erb
<div id="requestDoc_container" style="display: none">
  <div id="requestDoc">
    <%= simple_form_for(@request_doc) do |f| %>
      <%= f.error_notification %>

      <div class="form-inputs">
        <%= f.input :from, placeholder: 'you want to request a document from who?', label: false %>
        <%= f.input :doc_name, placeholder: 'document name', label: false %>
        <%= f.input :by_date %>
        <%= f.text_area :description, label: false, placeholder:'Notes' %>
      </div>

      <div class="form-actions" style="display: none">
        <%= f.button :submit %>
      </div>
    <% end %>
  </div>
</div>

app/views/deals/_signatures.html.erb
<div id="signature_container" style="display: none">
	<div id="signature">
		<%= simple_form_for(@signature) do |f| %>
		  <%= f.error_notification %>

		  <div class="form-inputs">
		    <%= f.input :deal_id %>
		    <%= f.input :signedBy %>
		    <%= f.input :signature %>
		  </div>

		  <div class="form-actions">
		    <%= f.button :submit %>
		  </div>
		<% end %>
	</div>
</div>

app/views/deals/_upload.html.erb
<div class="workflow-step-form workflow-step-create top-left-arrow" data-step-type="document-create">
  <%= form_for @upload do |f| %>
  <div class="title">
    <h3>Upload a Document</h3>
  </div>

  <div class="form_elements">
    <input type="hidden" data-bind-user-id="step.who" value="" name="who">
    <fieldset>

      <label for="doc_name" class="light">I am uploading the</label>
      <div class="doc-input clearfix">
        <input  onchange="alert(event.fpfile.url)" data-fp-services="BOX,COMPUTER,DROPBOX,GITHUB,GOOGLE_DRIVE,GMAIL" data-fp-container="modal" data-fp-mimetypes="*/*" data-fp-apikey="A29Ez5WZDSLexZzbbJrIzz" type="filepicker" data-fp-class="btn btn-primary btn-large" style="display: none;">
        <span>AND</span>
        <input type="text" required="" data-bind-value="step.doc_name" placeholder="Name the document" value="" name="doc_name" id="doc_name">
      </div>
    </fieldset>

    <fieldset>
      <label for="notes" class="light">Notes</label>
      <%= f.text_area :description, label: false, placeholder:'Notes' %>
    </fieldset>

    <div class="form-actions">
      <a class="btn btn-large delete">Delete Step</a>
      <button class="btn btn-primary btn-large save">Save Progress</button>
    </div>
  </div>
  <% end %>
</div>

app/views/deals/_uploads.html.erb
<div id="upload_container" style="display: none">
	<div id="upload">
		<%= simple_form_for(@upload) do |f| %>
		  <%= f.error_notification %>
		  <div class="title">
		    <h3>Upload a Document</h3>
		  </div>
		  <div class="row">
		  	<div class="form-inputs">
			   <fieldset>
			      <label for="doc_name" class="light">I am uploading the</label>
			      <div class="doc-input clearfix">
			        <input  onchange="alert(event.fpfile.url)" data-fp-services="BOX,COMPUTER,DROPBOX,GITHUB,GOOGLE_DRIVE,GMAIL" data-fp-container="modal" data-fp-mimetypes="*/*" data-fp-apikey="A29Ez5WZDSLexZzbbJrIzz" type="filepicker" data-fp-class="btn btn-primary btn-large" style="display: none;">
			        <span>AND</span>
			        <input type="text" required="" data-bind-value="step.doc_name" placeholder="Name the document" value="" name="doc_name" id="doc_name">
			      </div>
			    </fieldset>
			   <%= f.text_area :description, label: false, placeholder:'Notes' %>
		    </div>
		  </div>
		  

		  <div class="form-actions" style="display: none">
		    <%= f.button :submit %>
		  </div>
		<% end %>
	</div>
</div>

app/views/deals/edit.html.erb
<h1>Editing deal</h1>

<%= render 'form' %>

<%= link_to 'Show', @deal %> |
<%= link_to 'Back', deals_path %>

app/views/deals/index.html.erb
<h1>Listing deals</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Company</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @deals.each do |deal| %>
  <tr>
    <td><%= deal.name %></td>
    <td><%= deal.company_id %></td>
    <td><%= link_to 'Show', deal %></td>
    <td><%= link_to 'Edit', edit_deal_path(deal) %></td>
    <td><%= link_to 'Destroy', deal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Deal', new_deal_path %>

app/views/deals/new.html.erb
<% content_for(:head) do %>
	<script type="text/javascript">
		$(document).ready(function(){
			
			$('#load_upload').click(function(){
				$('#upload_container').toggle();
			});
			$('#load_requestDoc').click(function(){
				$('#requestDoc_container').toggle();
			});
			$('#load_approvals').click(function(){
				$('#approvals_container').toggle();
			});
			$('#load_getSignature').click(function(){
				$('#getSignature_container').toggle();
			});
		});
	</script>
<% end %>

<div class="span12 subheader">
  <div class="container">
	    <div data-block="page_title" class="page-title light">
	      Create a Deal
	    </div>
  </div>
</div>
<div id="page" class="id">
	<div class="container gutter">
		<div id="content" class="base">
			<div id="content">
				<div id="deal-builder">
					<form>
						<div class='row'>
							<div class="span2 deal-builder-sidebar">
						      <h3>Step 1</h3>
						      <h4>Select Company</h4>
						    </div>
						    <div class="10">
						    	<div class="controls controls-row deal-builder-name-controls clearfix">
						    		<div id="s2id_autogen1" class="select2-container span5 input-company">
						    			<%= render 'company' %>
						    		</div>
						    	</div>
						    </div>
						</div>
						<div class='row'>
							<div class="span2 deal-builder-sidebar">
						      <h3>Step 2</h3>
						      <h4>Deals Name</h4>
						    </div>
						    <div class="10">
						    	<div class="controls controls-row deal-builder-name-controls clearfix">
						    		<div id="s2id_autogen1" class="select2-container span5 input-company">
						    			<%= render 'deal' %>
						    		</div>

						    	</div>
						    </div>
						</div>
						<div class="row workflow-row">
							<div class="span2 deal-builder-sidebar">
						      <h3>Step 3</h3>
						      <h4>Add Steps</h4>
						    </div>
						    <div class="span2 workflow-menu-bar">
						    	<ul class="unstyled workflow-menu" data-tpl-template="dealer/workflow-menu" style="top: 0px;">
						    		<li class="workflow-item">
						    				<div id="box1">
							    				<div id="sbox">
						    						<p data-icon="a" class="pictos workflow-element-icon"></p>
						    						<a href="#" id="load_upload"><p class="workflow-element-name">UPLOAD A DOCUMENT</p></a>	
							    				</div>								    		
							    			</div>
						    			
						    		</li>
						    		<li class="workflow-item">
						    			<div id="">
						    			</div>
										<div id="box2">
											<p data-icon="a" class="pictos workflow-element-icon"></p>
											<a href="#" id="load_requestDoc"><p class="workflow-element-name">REQUEST A DOCUMENT</p></a>								
						    			</div>
									</li>
						    		<li class="workflow-item">
						    			<div id="">
						    			</div>
										<div id="box1">
											<p data-icon="a" class="pictos workflow-element-icon"></p>
											<a href="#" id="load_approvals"><p class="workflow-element-name">GET APPROVAL</p></a>								    		
						    			</div>
									</li>
									<li class="workflow-item">
										<div id="">
						    			</div>
										<div id="box2">
											<p data-icon="a" class="pictos workflow-element-icon"></p>
											<a href="#" id="load_getSignature"><p class="workflow-element-name">GET A SIGNATURE</p></a>								    		
						    			</div>
									</li>
						    	</ul>
						    </div>
						    <div class="span8 deal-builder-workflow">

								<div class="workflow-selection">
									<div class="workflow-items">
										<div>
											<%= render 'uploads' %>
											<%= render 'approvals' %>
											<%= render 'requestDoc' %>
											<%= render 'getSignature' %>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="row workflow-row">
						      <div class="span2 deal-builder-sidebar">
						        <h3>Step 4</h3>
						        <h4>Create The Deal</h4>
						      </div>
						      <div class="span10 workflow-form">
						        <div class="form-actions workflow-actions">
						          <button class="btn btn-primary btn-large workflow-save disabled" disabled="disabled">Create This Deal</button>
						          <%= link_to 'Back to deals', deals_path %><br/>
						        </div>
						      </div>
						  </div>
					</form>
					
				</div>
			</div>
				
		</div>
	</div>
</div>

app/views/deals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @deal.name %>
</p>

<p>
  <b>Company:</b>
  <%= @deal.company_id %>
</p>


<%= link_to 'Edit', edit_deal_path(@deal) %> |
<%= link_to 'Back', deals_path %>