config/routes.rb
Glider::Application.routes.draw do
  resources :deal_members


  resources :inviteds
  resources :companies
  resources :comments
  resources :signatures
  resources :get_signatures
  resources :approvals
  resources :request_docs
  resources :uploads
  resources :deals

  match '/about',           to: 'static_pages#about'
  match '/contact',         to: 'static_pages#contact'
  match '/help',            to: 'static_pages#help'
  match '/documentation',   to: 'static_pages#documentation'
  match '/terms',           to: 'static_pages#terms'

  mount StripeEvent::Engine => '/stripe'
  get "content/gold"
  get "content/silver"
  get "content/platinum"
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  match '/pricing',           to: 'home#pricing'
  devise_for :users, :controllers => { :registrations => 'registrations' }
  devise_scope :user do
    put 'update_plan', :to => 'registrations#update_plan'
    put 'update_card', :to => 'registrations#update_card'
  end
  resources :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    else
      can :view, :silver if user.has_role? :silver
      can :view, :gold if user.has_role? :gold
      can :view, :platinum if user.has_role? :platinum
    end
  end
end

app/models/approval.rb
class Approval < ActiveRecord::Base
  attr_accessible :by_date, :description, :names
  belongs_to :deals
  belongs_to :uploads
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :comments
  belongs_to :deals
end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :company
  has_many :deals, :dependent => :destroy
end

app/models/deal.rb
class Deal < ActiveRecord::Base
  attr_accessible :name

  belongs_to :companies
  has_many :users, :through => :deal_members
  has_one :uploads
  has_many :approvals
  has_many :comments
  has_many :signatures
  has_many :request_docs
  has_many :inviteds
end

app/models/deal_member.rb
class DealMember < ActiveRecord::Base
  attr_accessible :names
  belongs_to :users
  belongs_to :deals
end

app/models/get_signature.rb
class GetSignature < ActiveRecord::Base
  attr_accessible :by_date, :from
  belongs_to :uploads
end

app/models/invited.rb
class Invited < ActiveRecord::Base
  attr_accessible :email, :full_names, :user_type
  belongs_to :deals
end

app/models/request_doc.rb
class RequestDoc < ActiveRecord::Base
  attr_accessible :by_date, :description, :from
  belongs_to :deals
  belongs_to :uploads
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/signature.rb
class Signature < ActiveRecord::Base
  attr_accessible :signature, :signedBy
  belongs_to :deals
end

app/models/upload.rb
class Upload < ActiveRecord::Base
  attr_accessible :description, :filepicker_url

  has_many :request_docs
  has_many :approvals
  has_one :get_signatures
  belongs_to :deals
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :deals, :through => :deal_members
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :stripe_token, :coupon
  attr_accessor :stripe_token, :coupon
  before_save :update_stripe
  before_destroy :cancel_subscription

  def update_plan(role)
    self.role_ids = []
    self.add_role(role.name)
    unless customer_id.nil?
      customer = Stripe::Customer.retrieve(customer_id)
      customer.update_subscription(:plan => role.name)
    end
    true
  rescue Stripe::StripeError => e
    logger.error "Stripe Error: " + e.message
    errors.add :base, "Unable to update your subscription. #{e.message}."
    false
  end
  
  def update_stripe
    return if email.include?(ENV['ADMIN_EMAIL'])
    return if email.include?('@example.com') and not Rails.env.production?
    if customer_id.nil?
      if !stripe_token.present?
        raise "Stripe token not present. Can't create account."
      end
      if coupon.blank?
        customer = Stripe::Customer.create(
          :email => email,
          :description => name,
          :card => stripe_token,
          :plan => roles.first.name
        )
      else
        customer = Stripe::Customer.create(
          :email => email,
          :description => name,
          :card => stripe_token,
          :plan => roles.first.name,
          :coupon => coupon
        )
      end
    else
      customer = Stripe::Customer.retrieve(customer_id)
      if stripe_token.present?
        customer.card = stripe_token
      end
      customer.email = email
      customer.description = name
      customer.save
    end
    self.last_4_digits = customer.active_card.last4
    self.customer_id = customer.id
    self.stripe_token = nil
  rescue Stripe::StripeError => e
    logger.error "Stripe Error: " + e.message
    errors.add :base, "#{e.message}."
    self.stripe_token = nil
    false
  end
  
  def cancel_subscription
    unless customer_id.nil?
      customer = Stripe::Customer.retrieve(customer_id)
      unless customer.nil? or customer.respond_to?('deleted')
        if customer.subscription.status == 'active'
          customer.cancel_subscription
        end
      end
    end
  rescue Stripe::StripeError => e
    logger.error "Stripe Error: " + e.message
    errors.add :base, "Unable to cancel your subscription. #{e.message}."
    false
  end
  
  def expire
    UserMailer.expire_email(self).deliver
    destroy
  end
  
end

app/helpers/approvals_helper.rb
module ApprovalsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/content_helper.rb
module ContentHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inviteds_helper.rb
module InvitedsHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to "my app", root_path, :class => 'brand' %>
  </small>
    
    <p>© Copyright 2013. All rights reserved.</p>
    <nav>
      <ul>
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Contact", contact_path %></li>
          <li><%= link_to "Help & support", help_path %></li>
       </ul>
    </nav>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<header class="navbar navbar-fixed-top ">
  <nav class="navbar-inner">    
      <ul>
        <% if user_signed_in? %>
          <%= link_to "Glider App", deals_path, :class => 'brand' %>

          <div  class="nav pull-right">
            <li><%= link_to 'Edit account', edit_user_registration_path %></li>
            <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
            <li><%= link_to 'Create New Deal', new_deal_path %></li>
            <% if current_user.has_role? :admin %>
              <li><%= link_to 'Admin', users_path %></li>
            <% end %>
          </div>
          
        <%else%>
          <%= link_to "my app", root_path, :class => 'brand' %>
          <div class="nav pull-right">
            <li><%= link_to "pricing", pricing_path %></li>
            <li><%= link_to 'Sign up', new_user_registration_path %></li>
            <li><%= link_to "Help & support", help_path %></li>
            <li><%= link_to 'Login', new_user_session_path %></li>
          </div>
        <% end %>
      </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<div id="wrapper">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Glider" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Glider" %>">
    
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= filepicker_js_include_tag %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <div class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </div>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
  <%= render 'layouts/footer' %>
</div>
</html>